### ISSUE TITLE
Build.gradle failure because of Java 8

### ISSUE THREAD

**Issue by yoavst** [echsylon/atlantis#17] opened 2016-07-12 14:14 UTC
Why does the library requires Java 8? Java 8 is not yet supported for Android (If you are not using Jack and Jill).

```
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
```

**Comment by echsylon** [comment] 2016-07-13 06:28
A valid question! The project depends on the Retrolambda plugin to enable lambda expressions, which in turn requires Java 8 at some point. I think, though, that one could play a bit more with the gradle `compileOptions` directive, and especially the `sourceCompatibility` and `targetCompatibility` attributes when building the Atlantis library from source. I'll look into this soon.

Meanwhile the suggested walkaround is to compile any target projects with Java 8. If you have the time and feel for it, you're ofcourse more than welcome to contribute any own solutions or share any further findings and suggestions in this thread.

**Comment by yoavst** [comment] 2016-07-14 07:00
AFAIK, using retro lambda should make the jar using Java 7.

**Comment by echsylon** [comment] 2016-07-18 10:38
Sorry for the late response. You caught me in the middle of a vacation which I spend abroad with my family.

You may very well be right on the Retrolambda java version dependency. I have made some minor adjustments in the Atlantis gradle configuration which seems to resolve the issue in my test bench. Could you please verify if version 1.3.1 of the library works as you expect? If not, please feel free to re-open this ticket.

**Comment by echsylon** [comment] 2016-10-27 14:02
This issue is still observed. Re-opening.

**Comment by echsylon** [comment] 2016-10-27 19:57
Now we seem to have a verified fix for this bug (again).

Internally the Atlantis library makes use of the Retrolambda plugin which enables Java 8 Lambda expressions on non-Java 8 platforms. The issue seems to have been caused by a combination of at least two unfortunate assumptions:

1. The first assumption was that the Android gradle `compileOptions` configuration alone would be enough to to force Java 7 bytecode output when building the final JAR's.

2. The second assumption was that the Retrolambda plugin replaced any `javac` output before allowing unleashing the Android `dex`-ing.

A close look at the issue made it clear both assumptions were wrong. The change which now seems to fix the issue consists of forcing the Retrolambda plugin to produce Java 7 bytecode _and_ manually picking the transformed classes produced by Retrolambda and putting them into the produced JAR instead.

Sorry for having fooled you @yoavst with the previous faux fix. This time it should work as expected.

**Closed** 2016-10-27 19:57 UTC
Labels: bug
